export const CART_STORAGE_KEY = "lipslab_cart";
export const SHOPIFY_QUEUE_KEY = "lipslab_shopify_queue";
export const SHOPIFY_GLOSS_VARIANT_ID = 47048949006593;
export const SHOPIFY_BATOM_VARIANT_ID = 47049932833025;

export const GLITTER_LABELS: Record<number, string> = {
  1: "Crystal",
  2: "Bronze",
  3: "Fuchsia",
  4: "Garnet",
  5: "Opal",
  6: "Pink",
  7: "Pink Diamond",
  8: "Russet",
  9: "Silver",
  10: "Star Ruby",
  11: "Violet",
  12: "Antique Gold",
  13: "Brass",
  14: "Copper",
  15: "Coral",
  16: "Fire Opal",
  17: "Gold",
  18: "Sienna",
  19: "Sand",
  20: "Carnelian",
  21: "Champagne",
  22: "Pink Gold",
  23: "Rose Gold",
  24: "Alexandrite",
  25: "Azurite",
  26: "Chrysolite",
  27: "Morganite",
  28: "Indigolite",
  29: "Pink (Foil)",
  30: "Bronze (Foil)",
  31: "Gold (Foil)",
  32: "Silver (Foil)",
  33: "Red (Foil)",
  34: "Rainbow (Foil)",
  35: "Dazzle Dust",
  36: "Gold Dust",
  37: "Diamond Dust",
};
