export const GLITTER_LABELS: Record<number, string> = {
  1: "Crystal",
  2: "Bronze",
  3: "Fuchsia",
  4: "Garnet",
  5: "Opal",
  6: "Pink",
  7: "Pink Diamond",
  8: "Russet",
  9: "Silver",
  10: "Star Ruby",
  11: "Violet",
  12: "Antique Gold",
  13: "Brass",
  14: "Copper",
  15: "Coral",
  16: "Fire Opal",
  17: "Gold",
  18: "Sienna",
  19: "Sand",
  20: "Carnelian",
  21: "Champagne",
  22: "Pink Gold",
  23: "Rose Gold",
  24: "DIAMOND DUST",
  25: "Gold DUST",
  26: "Alexandrite",
  27: "Azurite",
  28: "Chrysolite",
  29: "Morganite",
  30: "Indigolite",
  31: "Blush",
  32: "Bronzed",
  33: "Nugget",
  34: "Platinum",
  35: "Ruby",
  36: "Twinkle",
};
